const songs = [
    'Saiyaan Ji Yo Yo Honey Singh',
    'Falling Trevor Daniel',
    'Shayad Pritam',
    'Malang (Title Track) [From "Malang - Unleash The Madness"] Ved Sharma',
    'Genda Phool (feat. Payal Dev) Badshah',
    'Humraah (From "Malang - Unleash The Madness") Sachet Tandon',
    'Baila Conmigo (with Rauw Alejandro) Selena Gomez',
    'You (with Marshmello & Vance Joy) benny blanco',
    'Higher (feat. iann dior) Clean Bandit',
    'Element Pop Smoke',
    'HUMBLE. Kendrick Lamar',
    'Sucker for Pain (with Wiz Khalifa, Imagine Dragons, Logic & Ty Dolla $ign feat. X Ambassadors) Lil Wayne',
    'Dip (feat. Nicki Minaj) (feat. Nicki Minaj) Tyga',
    'goosebumps Travis Scott',
    'Walk It Talk It Migos',
    'King Kunta Kendrick Lamar',
    'Swang Rae Sremmurd',
    "I'm the One (feat. Justin Bieber, Quavo, Chance the Rapper & Lil Wayne) DJ Khaled",
    'Another Love Tom Odell',
    'People Help the People Birdy',
    'unravel (acoustic version) - Acoustic Version TK from Ling tosite sigure',
    'Isabella\'s Lullaby (from "The Promised Neverland") AmaLee',
    'asphyxia Cö Shu Nie',
    'Kokoronashi majiko',
    "Can't Hold Us - feat. Ray Dalton Macklemore & Ryan Lewis",
    'Somebody That I Used To Know Gotye',
    'River Flows In You Yiruma',
    "Comptine d'un autre été, l'après-midi Yann Tiersen",
    'You Raise Me Up Josh Groban',
    'Hope XXXTENTACION',
    'Close To Me Ellie Goulding',
    'Hope The Chainsmokers',
    'Baarishein Anuv Jain',
    'Why Did I Answer? Porsche Love',
    'Baari Bilal Saeed',
    'Big Gangsta Kevin Gates',
    "Famous (I'm The One) (feat. Yo Gotti & DeJ Loaf) Mozzy",
    'Beware Big Sean',
    'The Thrill Wiz Khalifa',
    'Dior Pop Smoke',
    'good 4 u Olivia Rodrigo',
    'Kiss Me More (feat. SZA) Doja Cat',
    'Butter BTS',
    'MONTERO (Call Me By Your Name) Lil Nas X',
    'Arcade Duncan Laurence',
    'WITHOUT YOU The Kid LAROI',
    'Leave The Door Open Bruno Mars',
    'Levitating (feat. DaBaby) Dua Lipa',
    'Peaches (feat. Daniel Caesar & Giveon) Justin Bieber',
    'Save Your Tears (with Ariana Grande) (Remix) The Weeknd',
    'deja vu Olivia Rodrigo',
    'Beautiful Mistakes (feat. Megan Thee Stallion) Maroon 5',
    "Sygrayem (Let's Play) Carlos Rafael Rivera",
    'Our Song Anne-Marie',
    'Leave Before You Love Me (with Jonas Brothers) Marshmello',
    'Build a Bitch Bella Poarch',
    'Heartbreak Anthem (with David Guetta & Little Mix) Galantis',
    'unravel TK from Ling tosite sigure',
    'ブルーバード Ikimonogakari',
    'Lucid Dreams Juice WRLD',
    'Experience Ludovico Einaudi',
    'Hello (feat. A Boogie Wit da Hoodie) Pop Smoke',
    'Deep End Freestyle Sleepy Hallow',
    'Gang Shit No Lame Shit Key Glock',
    'Sideways ILLENIUM',
    'Nightlight ILLENIUM',
    'Night Changes One Direction',
    'Alive Empire of the Sun',
    'A Thousand Years Christina Perri',
    "I Know It's You Guards",
    'A Thousand Years (feat. Steve Kazee) - Pt. 2; The Twilight Saga: Breaking Dawn Soundtrack Christina Perri',
    'Main Title Carlos Rafael Rivera',
    "Beth's Story Carlos Rafael Rivera",
    'Methuen Home For Children 1957 Carlos Rafael Rivera',
    "The Scholar's Mate Carlos Rafael Rivera",
    "You're Gloating Carlos Rafael Rivera",
    'Training With Mr. Schaibel Carlos Rafael Rivera',
    'Mishri Anuv Jain',
    'SugarCrash! ElyOtto',
    'Higher Power Coldplay',
    'Break My Heart Myself (feat. Travis Barker) Bebe Rexha',
    'Echo (with KSHMR) Armaan Malik',
    'Astronomy Conan Gray',
    'Alag Aasmaan Anuv Jain',
    'Sau Aasmaan Armaan Malik',
    'Besabriyaan Armaan Malik',
    'What If (I Told You I Like You) Johnny Orlando',
    'Everybody Wants You Johnny Orlando',
    'Two of Us Louis Tomlinson',
    'Wonder Shawn Mendes',
    'Before You Go Lewis Capaldi',
    'A Whole New World (End Title) - From "Aladdin" ZAYN',
    'Just Like You Louis Tomlinson',
    'What A Time (feat. Niall Horan) Julia Michaels',
    'Interstellar Main Theme - Piano Version Patrik Pietschmann',
    'Interstellar- Main Theme Geek Music',
    'Without Me (with Juice WRLD) Halsey',
    'Without Me Halsey',
    'you broke me first Tate McRae',
    'Jalebi Baby Tesher',
    'Switch It Up (feat. sokodomo) - Prod. Cha Cha Malone JAY B',
    'Mera Mann Kehne Laga Falak Shabir',
    'Good Years ZAYN',
    'Grenade Bruno Mars',
    'Talking to the Moon Bruno Mars',
    'My Heart Will Go On - Love Theme from "Titanic" Céline Dion',
    'Stereo Hearts (feat. Adam Levine) Gym Class Heroes',
    'Stereo Love Edward Maya',
    'Righteous Juice WRLD',
    '734 Juice WRLD',
    "Life's A Mess II (with Clever & Post Malone) Juice WRLD",
    'Lucid Dreams (feat. Lil Uzi Vert) - Remix Juice WRLD',
    'Come & Go (with Marshmello) Juice WRLD',
    'Blastoff (feat. Juice Wrld & Trippie Redd) Internet Money',
    'Stay High Juice WRLD',
    'Bandit (with YoungBoy Never Broke Again) Juice WRLD',
    'No Me Ame Rvssian',
    'One Dance Drake',
    'Lean On Major Lazer',
    'Sunflower - Spider-Man: Into the Spider-Verse Post Malone',
    'Rolling in the Deep Adele',
    '7 rings Ariana Grande',
    'Wake Me Up Avicii',
    'Love The Way You Lie Eminem',
    'Morning Zara Larsson',
    'I Should Quit JESSIA',
    'Am I Good Enough Now? Carlos Rafael Rivera',
    'u love u (with Tate McRae) blackbear',
    'By Your Side (feat. Tom Grennan) Calvin Harris',
    'Lost Cause Billie Eilish',
    'seaside_demo SEB',
    'Last Train Home John Mayer',
    't r a n s p a r e n t s o u l feat. Travis Barker WILLOW',
    'Shape of You Ed Sheeran',
    'bad guy Billie Eilish',
    'Rather Be (feat. Jess Glynne) Clean Bandit',
    'Cocaine Pink Sweat$',
    'Honesty Pink Sweat$',
    'Mask Off Future',
    'Mask Off - Marshmello Remix Future',
    'Hymn for the Weekend - Seeb Remix Coldplay',
    'The Scientist Coldplay',
    'My Way Calvin Harris',
    'All Night The Vamps',
    'I Don’t Wanna Live Forever (Fifty Shades Darker) ZAYN',
    'Let Me Love You DJ Snake',
    'Adventure of a Lifetime Coldplay',
    'This Is What You Came For (feat. Rihanna) Calvin Harris',
    'Perfect Strangers Jonas Blue',
    'Perfect One Direction',
    'Jalebi Baby (Tesher x Jason Derulo) Tesher',
    'Love Again Dua Lipa',
    'Hide (feat. Seezyn) Juice WRLD',
    'Disrespectful Blueface',
    'Crooked Smile (feat. TLC) J. Cole',
    'Into Your Arms (feat. Ava Max) Witt Lowry',
    'Into Your Arms (feat. Ava Max) - BEAUZ Remix Witt Lowry',
    'anxiety (with FRND) blackbear',
    'Good Things Fall Apart vs. Sad Songs (With Said The Sky feat. Annika Wells) ILLENIUM',
    'If You Love Her Forest Blakk',
    'Take Me To Church Hozier',
    'Takeaway The Chainsmokers',
    'Call You Mine The Chainsmokers',
    "If I Can't Have You Shawn Mendes",
    'Lily Alan Walker',
    'Teeth 5 Seconds of Summer',
    'Hate Me Ellie Goulding',
    'Better Days OneRepublic',
    'Do You Mean The Chainsmokers',
    'Want You Back 5 Seconds of Summer',
    'One More Day (with Chandler Leighton) Jason Ross',
    'In the End Linkin Park',
    'Believer Imagine Dragons',
    'Radioactive Imagine Dragons',
    'Centuries Fall Out Boy',
    'Hall of Fame (feat. will.i.am) The Script',
    'Animals Maroon 5',
    'Tchaikovsky: Swan Lake, Op. 20, Act 2: Scene (Moderato) Pyotr Ilyich Tchaikovsky',
    'Hero (feat. Christina Perri) Cash Cash',
    'Goodbye To A World Porter Robinson',
    'Magic in the Air (feat. Ahmed Chawki) Magic System',
    'telepatía Kali Uchis',
    'E-ER (feat. Lil Yachty) DJ Scheme',
    'Ex Bitch XXXTENTACION',
    'Ga$ Money Xavy Rusan',
    'Yonaguni Bad Bunny',
    'Need To Know Doja Cat',
    'The Business Tiësto',
    'MONTERO (Call Me By Your Name) ASKØ',
    'Tokyo Drift Jenil',
    'Wants and Needs (feat. Lil Baby) Drake',
    'RAPSTAR Polo G',
    'Look Back at It A Boogie Wit da Hoodie',
    'Can We Kiss Forever? Kina',
    'Kiss Me Thru The Phone Soulja Boy',
    'Closer The Chainsmokers',
    'Something Just Like This The Chainsmokers',
    "Don't Let Me Down The Chainsmokers",
    'This Feeling The Chainsmokers',
    'Who Do You Love The Chainsmokers',
    'Roses The Chainsmokers',
    'Paris The Chainsmokers',
    'Sick Boy The Chainsmokers',
    'The Reaper The Chainsmokers',
    'Family The Chainsmokers',
    'Share Ruth B.',
    'Tell Me U Luv Me (with Trippie Redd) Juice WRLD',
    'Hide Away Daya',
    'One Moment in Time - Remastered Whitney Houston',
    'Lost Maroon 5',
    'EveryTime I Cry Ava Max',
    'Fingers Crossed Trevor Daniel',
    'Cloudy Day Tones And I',
    'Imagine - Tiësto Remix Ben Platt',
    'Lose Somebody Kygo',
    'Going Dumb Alesso',
    'Silence Marshmello',
    "I'm a Mess Bebe Rexha",
    'Alone, Pt. II Alan Walker',
    'Selfish Love (with Selena Gomez) DJ Snake',
    'Symphony (feat. Zara Larsson) Clean Bandit',
    'Gone Are The Days (feat. James Gillespie) Kygo',
    'Midnight (feat. Liam Payne) Alesso',
    'More Than You Know Axwell /\\ Ingrosso',
    'The Best Days (feat. Tabitha) Sam Feldt',
    'Lonely (with benny blanco) Justin Bieber',
    'Drag Me Down One Direction',
    'Lose My Mind DVBBS',
    'Body Back (feat. Maia Wright) - Deniz Koyu Remix Gryffin',
    'Think About You - Galantis Remix Kygo',
    'No Money Galantis',
    'Playing Mr. Ganz Carlos Rafael Rivera',
    'Ceiling Games Carlos Rafael Rivera',
    'First Day At School Carlos Rafael Rivera',
    'The Green Pills Carlos Rafael Rivera',
    'Kentucky State Championship 1963 Carlos Rafael Rivera',
    'Top Boards Carlos Rafael Rivera',
    'Playing Townes Carlos Rafael Rivera',
    'Playing Beltik Carlos Rafael Rivera',
    'The Lake - Cincinnati Carlos Rafael Rivera',
    'Playing Benny - Las Vegas 1966 Carlos Rafael Rivera',
    'Two Sides Of The Same Coin Carlos Rafael Rivera',
    'Mexico City Invitational 1966 Carlos Rafael Rivera',
    'Playing Girev I Carlos Rafael Rivera',
    'Playing Girev II Carlos Rafael Rivera',
    'Borgov I Carlos Rafael Rivera',
    'Beth Alone Carlos Rafael Rivera',
    'Ohio US Championship 1967 Carlos Rafael Rivera',
    'New York Carlos Rafael Rivera',
    'Training With Benny Carlos Rafael Rivera',
    'Paris Tournament 1967 Carlos Rafael Rivera',
    'Borgov II Carlos Rafael Rivera',
    'Jolene! Carlos Rafael Rivera',
    'Returning To Methuen Carlos Rafael Rivera',
    'Turning Point Carlos Rafael Rivera',
    'USSR Carlos Rafael Rivera',
    'Moscow Invitational 1968 Carlos Rafael Rivera',
    'Close Your Eyes Carlos Rafael Rivera',
    'Borgov III Carlos Rafael Rivera',
    'The Final Game Carlos Rafael Rivera',
    "Take It, It's Yours Carlos Rafael Rivera",
    'By Your Side Jonas Blue',
    'Throwback Delaney Jane',
    '2 Hearts (feat. Gia Koka) Sam Feldt',
    'Hear Me Say Jonas Blue',
    'Speechless (feat. Erika Sirola) - MOTi Remix Robin Schulz',
    'Higher (feat. iann dior) - Dimitri Vegas & Like Mike Remix Clean Bandit',
    'Dandelions Ruth B.',
    'Too Late (feat. Wiz Khalifa & Lukas Graham) - Riggi & Piros Remix Cash Cash',
    'Falling Harry Styles',
    'Space Melody (Edward Artemyev) (feat. Leony) VIZE',
    'Another Life (feat. Alida) Lucas & Steve',
    'Way Back Home (feat. Conor Maynard) - Sam Feldt Edit SHAUN',
    'Faded - Luke Christopher Remix Alan Walker',
    'Without You Mike Williams',
    'Be Kind (with Halsey) Marshmello',
    'Cheerleader - Felix Jaehn Remix Radio Edit OMI',
    'Daylight Klaas',
    'All We Need (feat. Shy Girls) - Dzeko & Torres Remix Radio Edit ODESZA',
    'SOS (feat. Aloe Blacc) Avicii',
    'Hearts on Fire - CORSAK & Willim Remix ILLENIUM',
    'You Know You Like It DJ Snake',
    'Fast Car Jonas Blue',
    'Sixteen Ellie Goulding',
    'In the Name of Love Martin Garrix',
    'Sweet Dreams Alan Walker',
    'Summer Thing Dragonette',
    'Whole Life Kaivon',
    "Don't Wanna Fall Seven Lions",
    'Excitement (feat. PARTYNEXTDOOR) Trippie Redd',
    'Body (Remix) [feat. ArrDee, E1 (3x3), ZT (3x3), Bugzy Malone, Buni, Fivio Foreign & Darkoo] Tion Wayne',
    'Stressed Out Twenty One Pilots',
    'Beauty and the Beast - from the Soundtrack "Beauty and the Beast" Céline Dion',
    'Another Love - Radio Edit Tom Odell',
    'working Tate McRae',
    'Reckless Madison Beer',
    'Solar Power Lorde',
    'cold/mess Prateek Kuhad',
    'Kho Gaye Hum Kahan Jasleen Royal',
    "i don't want to watch the world end with someone else Clinton Kane",
    'Knock Knock SoFaygo',
    'Hula Hoop OMI',
    'Pasadena Tinashe',
    'Feel Something Joshua Bassett',
    "Nothing's the Same Alexander 23",
    'You Should Run Moore Kismet',
    'Poison DJ Gollum',
    'DRXGS - Rawtek Remix Yellow Claw',
    'Shade of Yellow Griff',
    'Black Hole Griff',
    'FEFE 6ix9ine',
    'Magic Lil Skies',
    'Look at the Sky Porter Robinson',
    'So What (feat. A R I Z O N A) Louis The Child',
    'Taste of You (feat. Dove Cameron) Rezz',
    'Deep Blue William Black',
    'Gasoline (feat. Laura White) Cash Cash',
    'In Your Arms (with X Ambassadors) ILLENIUM',
    'WOW (with Emma Steinbakken) Matoma',
    'Shut The World Out Kasbo',
    'Moon Rider (feat. Wrabel) Jai Wolf',
    'I Love You. Kaivon',
    'Good Things Fall Apart (with Jon Bellion) ILLENIUM',
    'UCLA RL Grime',
    'The Bender (with Brando) Matoma',
    'Sweet Time Porter Robinson',
    'Big Love (with EARTHGANG & MNDR) Louis The Child',
    'Lost ILLENIUM',
    'Someone To You BANNERS',
    'Dernière Danse Yves V',
    'Summer Air Hardwell',
    'Impossible Shontelle',
    'Get Together David Guetta',
    'Enjoy Enjaami - Spotify Singles (with Dhee feat. Arivu & Santhosh Narayanan) DJ Snake',
    'Weekend Vibe (feat. Desi Crew) Jubël',
    'YUSO (feat. Lil Wayne & Saweetie) Kid Ink',
    'Wolves (feat. Post Malone) Big Sean',
    'New Love (feat. Ellie Goulding) Silk City',
    'My House - Chill Mix Elderbrook',
    'Lost Gareth Emery',
    'Slow Clap (with Saweetie) Gwen Stefani',
    'Glad You Came The Wanted',
    'Smile (with The Weeknd) Juice WRLD',
    'Wishing Well Juice WRLD',
    'Real Shit (with benny blanco) Juice WRLD',
    'Shots Imagine Dragons',
    'Stitches Shawn Mendes',
    "There's Nothing Holdin' Me Back Shawn Mendes",
    'Lost In Japan Shawn Mendes',
    'Treat You Better Shawn Mendes',
    'Señorita - Slowed + Reverb Dayscar',
    'Señorita Shawn Mendes',
    'Real Love Clean Bandit',
    'Beside You (feat. Georgia Ku) Matoma',
    "Don't Wanna Know - Ryan Riback Remix Maroon 5",
    "We're Coming Up Julie Bergan",
    'Floating Through Space Sia',
    'In My Blood Shawn Mendes',
    'Memories Maroon 5',
    'Imagination Shawn Mendes',
    'Rescue Me OneRepublic',
    'How Do You Sleep? Sam Smith',
    'Rewrite The Stars Zac Efron',
    'Dusk Till Dawn (feat. Sia) - Radio Edit ZAYN',
    'ME! (feat. Brendon Urie of Panic! At The Disco) Taylor Swift',
    'Love Me Like You Do Ellie Goulding',
    "It's You Ali Gatie",
    'Break My Heart Dua Lipa',
    'Beautiful People (feat. Khalid) Ed Sheeran',
    'Liar Camila Cabello',
    'Sucker Jonas Brothers',
    'Cheating on You Charlie Puth',
    'Back To You - From 13 Reasons Why – Season 2 Soundtrack Selena Gomez',
    'Happier Ed Sheeran',
    'So Am I (feat. NCT 127) Ava Max',
    'Personal HRVY',
    'That Girl Olly Murs',
    'Woman Like Me (feat. Nicki Minaj) Little Mix',
    'Best Part of Me (feat. YEBBA) Ed Sheeran',
    'Watermelon Sugar Harry Styles',
    'Sing It With Me JP Cooper',
    "If I Can't Have You - Gryffin Remix Shawn Mendes",
    'Looking at Me Sabrina Carpenter',
    'I Got You - Cheat Codes Remix Bebe Rexha',
    'Choo Lo The Local Train',
    'Dil Mere The Local Train',
    'Aaftaab The Local Train',
    'Aaoge Tum Kabhi The Local Train',
    'Khudi The Local Train',
    'Dilnawaz The Local Train',
    'Kaisey Jiyun The Local Train',
    'Mizaaj The Local Train',
    'Mere Yaar The Local Train',
    'Solo (feat. Demi Lovato) Clean Bandit',
    'Say My Name David Guetta',
    "We Don't Care Sigala",
    'Without You (feat. Sandro Cavazza) Avicii',
    'Taki Taki (feat. Selena Gomez, Ozuna & Cardi B) DJ Snake',
    '2002 Anne-Marie',
    'Rewrite The Stars (with James Arthur & Anne-Marie) James Arthur',
    'Girls Like You (feat. Cardi B) - Cardi B Version Maroon 5',
    'Happy Now Zedd',
    'No Lie Sean Paul',
    'Just My Type The Vamps',
    'Lonely Together (feat. Rita Ora) Avicii',
    'I Like Me Better Lauv',
    'Timber (feat. Ke$ha) Pitbull',
    'Black Mask (feat. Pop Smoke) Jay Gwuapo',
    'Lost bülow',
    'Chain My Heart Topic',
    'Eastside (with Halsey & Khalid) benny blanco',
    'Sky Mike Candys',
    'Bad Habits Ed Sheeran',
    "I Don't Do Drugs (feat. Ariana Grande) Doja Cat",
    '18 Jeremy Zucker',
    'You Right Doja Cat',
    'dancing in the kitchen LANY',
    'Let Me Know Surfaces',
    'Funny Zedd',
    'BED Joel Corry',
    'No Chill (feat. Lil Xxel) Cheat Codes',
    'Unfamiliar Seeb',
    'Feels Jax Jones',
    'Demons Imagine Dragons',
    'Pavane, Op. 50 Gabriel Fauré',
    'Merry-Go-Round(人生のメリーゴーランド) Joe Hisaishi',
    'Scheherazade: The Tale of the Kalendar Prince Nikolai Rimsky-Korsakov',
    'Masquerade (Suite): 1. Waltz - Excerpt Aram Khachaturian',
    'Violin Concerto in D Major, Op. posth., No. 2: Adagio Joseph Boulogne Chevalier de Saint-Georges',
    'I Want It That Way Backstreet Boys',
    'Aicha Outlandish',
    'Flightless Bird, American Mouth Iron & Wine',
    'A Sky Full of Stars Coldplay',
    'Renegades X Ambassadors',
    'Maps Maroon 5',
    'Shots - Broiler Remix Imagine Dragons',
    'Ode To My Family The Cranberries',
    'Zombie The Cranberries',
    'Linger The Cranberries',
    'In Cold Light (Alexandra Hamilton-Ayres Rework) Vanbur',
    'Back To The Sky Ólafur Arnalds',
    'Wandering II - Ed Carlsen Rework Eydís Evensen',
    'Retour Tony Anderson',
    'Mere Rashke Qamar (From "Baadshaho") Nusrat Fateh Ali Khan',
    "I Don't Know Why NOTD",
    'Break Me Down Autograf',
    'On My Life Cheat Codes',
    'Round and Round Empyre One',
    'Let You Know Flume',
    'Strong London Grammar',
    'Ghalat Fehmi - From "Superstar" Asim Azhar',
    'Tera Ghata Gajendra Verma',
    'Titans (feat. Sia & Labrinth) - Imanbek Remix Major Lazer',
    'Hero Faouzia',
    'Aakhri Salaam The Local Train',
    'Yeh Zindagi Hai The Local Train',
    'Bandey The Local Train',
    'All I Wanna Do Martin Jensen',
    'Even When/The Best Part - From "High School Musical: The Musical: The Series (Season 2)" Olivia Rodrigo',
    'Run OneRepublic',
    'Your Power Billie Eilish',
    'Electric - Pokemon 25 Version Katy Perry',
    'FUCKBOY Dixie',
    'drivers license Olivia Rodrigo',
    "Don't Start Now Dua Lipa",
    'Anyone Justin Bieber',
    'Monster (Shawn Mendes & Justin Bieber) Shawn Mendes',
    'Goodbye Imanbek',
    'The Rose Song - From "High School Musical: The Musical: The Series (Season 2)" Olivia Rodrigo',
    'exile (feat. Bon Iver) Taylor Swift',
    'Death By A Thousand Cuts - Live From Paris Taylor Swift',
    'Look What You Made Me Do Taylor Swift',
    'long story short Taylor Swift',
    'closure Taylor Swift',
    'Fifteen Taylor Swift',
    'Sexy Bitch (feat. Akon) David Guetta',
    'Party Rock Anthem LMFAO',
    'New Thang Redfoo',
    'Counting Stars OneRepublic',
    'Feel Good (feat. Daya) Gryffin',
    '2U (feat. Justin Bieber) David Guetta',
    'Pretty Please Dua Lipa',
    'Fractures ILLENIUM',
    'Galway Girl Ed Sheeran',
    'Locked Away (feat. Adam Levine) R. City',
    'Show Me Love MR.BLACK',
    'Let You Down NF',
    'Kiss and Make Up Dua Lipa',
    'Sweet Harmony LUNAX',
    'Talk To Me (feat. Conor Maynard & RANI) - Sam Feldt Edit Möwe',
    'Arcade (feat. FLETCHER) Duncan Laurence',
    'Revolver bülow',
    'All Too Well Jake Scott',
    'Die For a Man (feat. Lil Uzi Vert) Bebe Rexha',
    'Telling Myself Joshua Bassett',
    'I Would Like - R3hab Remix Zara Larsson',
    'Diamonds Rihanna',
    'Agar Tum Saath Ho Alka Yagnik',
    'Agar Tum Mil Jao Shreya Ghoshal',
    "I'm Not Mad Halsey",
    'Main Rahoon Ya Na Rahoon Armaan Malik',
    'Scars To Your Beautiful Alessia Cara',
    'IDK You Yet Alexander 23',
    'A Little Bit Yours JP Saxe',
    'Everyone Changes Kodaline',
    'Bad boy Marwa Loud',
    'Ransom (with Juice WRLD) - Remix Lil Tecca',
    'Startender (feat. Offset and Tyga) A Boogie Wit da Hoodie',
    'Fire On Fire Sam Smith',
    'Neighbor (feat. Travis Scott) Juicy J',
    'One More Time (feat. Alida) - Klingande Remix Robin Schulz',
    "Talk Why Don't We",
    "Can't Go Home (feat. Adam Lambert) - Radio Edit Steve Aoki",
    '(They Long To Be) Close To You The Cranberries',
    "We Don't Talk Anymore (feat. Selena Gomez) - Attom Remix Charlie Puth",
    'Worship MAX',
    'Jar of Hearts Christina Perri',
    'Echo (feat. blackbear) Maroon 5',
    'Sometimes Kodaline',
    'Spirits The Strumbellas',
    "This One's for You (feat. Zara Larsson) (Official Song UEFA EURO 2016) David Guetta",
    'Love Yourself Justin Bieber',
    'Play Hard (feat. Ne-Yo & Akon) - New Edit David Guetta',
    'Shallow Lady Gaga',
    'Heathens Twenty One Pilots',
    'You And Me The Cranberries',
    'Mine Bazzi',
    'In The Name Of Love - The Him Remix Martin Garrix',
    'Nobody Greyson Chance',
    "Big Plans Why Don't We",
    'Train Wreck James Arthur',
    'My House Flo Rida',
    'Secrets OneRepublic',
    '1-800-273-8255 Logic',
    'DRXGS Yellow Claw',
    'All Time Low Kurt Hugo Schneider',
    'Real Friends Camila Cabello',
    'She Said FLETCHER',
    'die without u LØLØ',
    'New Rules Dua Lipa',
    'Stranger Blanks',
    'im all alone lael',
    'Spin The Block (feat. Future) Lil Durk',
    'detest me glaive',
    'Runaway 6VIB3Z',
    'BedRock Young Money',
    "Buy U a Drank (Shawty Snappin') (feat. Yung Joc) T-Pain",
    'Heat Waves Glass Animals',
    'Let Them Know Mabel',
    'Our World (feat. Daniele Sorrentino) Blasterjaxx',
    'Scared to Be Lonely Martin Garrix',
    "It Ain't Me (with Selena Gomez) Kygo",
    'Mama Jonas Blue',
    'Faded Alan Walker',
    'Heather Conan Gray',
    'At My Worst Pink Sweat$',
    'Mood (feat. iann dior) 24kGoldn',
    'Hold On Justin Bieber',
    'Hate Me (with Juice WRLD) Ellie Goulding',
    'Circles Post Malone',
    'Signal TK from Ling tosite sigure',
    "The Blower's Daughter Damien Rice",
    "i'm so tired... Lauv",
    'Met Him Last Night - Dave Audé Remix Demi Lovato',
    'Freaks Surf Curse',
    'Cold Light KC Lights',
    'Just Dance EQRIC',
    'Lift Your Energy Eden Prince',
    'Payphone Maroon 5',
    'Seasons - NIVIRO Remix Rival',
    'S&M Remix Rihanna',
    'Blinding Lights The Weeknd',
    'Umbrella Ember Island',
    'Cold Skin Seven Lions',
    'Better Not (with Wafia) Louis The Child',
    'I Get You Kasbo',
    'Line Of Sight (Reprise) (feat. WYNNE & Mansionair) ODESZA',
    'Only One I Need William Black',
    'All Eyes On Me Bo Burnham',
    'STAY (with Justin Bieber) The Kid LAROI',
    'Just A Mess Tones And I',
    'Renegade (feat. Taylor Swift) Big Red Machine',
    'Demeanor (feat. Dua Lipa) Pop Smoke',
    'Good Life (with G-Eazy & Kehlani) G-Eazy',
    'Bamboléo Gipsy Kings',
    'Feel This Moment (feat. Christina Aguilera) Pitbull',
    "Don't Leave Me Now Lost Frequencies",
    'Sleepover Litany',
    'All My Friends AJ Mitchell',
    'Not Allowed TV Girl',
    'Brush Fire Gracie Abrams',
    'Butterflies MAX',
    'Shower Becky G',
    'I Like Me Better Anthony de la Torre',
    'Emptiness Zodiac Wave',
    'If I Could Brynn Cartelli',
    'Bright Eyes Art Garfunkel',
    'Game of Thrones - Theme London Music Works',
    'People Watching Conan Gray',
    'The Rains of Castamere Ramin Djawadi',
    'The Rains of Castamere (From the HBO® Series Game Of Thrones - Season 4) Ramin Djawadi',
    'The Rains Of Castomere The National',
    'Forever Lewis Capaldi',
    'Power is Power (feat. The Weeknd & Travis Scott) SZA',
    'All I Want (Floorplan Remix) [Extended Mix] (feat. Andrea Martin) Secondcity',
    'Closer Jaden Thompson',
    "What's Up Gaullin",
    'When I Need You Céline Dion',
    'Beautiful Now Zedd',
    "Won't Bite (feat. Smino) Doja Cat",
    "She's My Collar (feat. Kali Uchis) Gorillaz",
    'Hold It Against Me Britney Spears',
    'I miss you, I’m sorry Gracie Abrams',
    'Fingers Crossed (with Julia Michaels) Trevor Daniel',
    'Mood (Remix) feat. Justin Bieber, J Balvin & iann dior 24kGoldn',
    'NUMB Chri$tian Gate$',
    'Hate You + Love You (feat. AJ Mitchell) Cheat Codes',
    'Party Girl StaySolidRocky',
    'Heart Attack Demi Lovato',
    'Love Is Gone - Acoustic Dylan Matthew',
    'Home (with Machine Gun Kelly, X Ambassadors & Bebe Rexha) Machine Gun Kelly',
    'Changes Hayd',
    'Back To U SLANDER',
    'Time NF',
    '7UP Boy In Space',
    'Hate The Way (feat. blackbear) G-Eazy',
    'lie to me Ali Gatie',
    'Do You Believe Ali Gatie',
    "i hate u, i love u (feat. olivia o'brien) gnash",
    'ANGELS & DEMONS jxdn',
    "I Don't Want You Back AJ Mitchell",
    'Chasing_(Demo) NF',
    'hot girl bummer blackbear',
    'idfc - Tarro Remix blackbear',
    'Ridiculous Thoughts The Cranberries',
    "When We Were Young Dolores O'Riordan",
    "Human Spirit Dolores O'Riordan",
    'Pain - Remastered Blackfield',
    'Send Me An Angel Scorpions',
    'Under Your Spell The Birthday Massacre',
    'Frozen Madonna',
    'Stay Zedd',
    'Bartholomew The Silent Comedy',
    'Loki Green Theme Natalie Holt',
    'Photograph Ed Sheeran',
    'SAD! XXXTENTACION',
    'Everybody Dies In Their Nightmares XXXTENTACION',
    'Losing Interest itssvd',
    'Tory lanez freestyle  Battieboyspodcast',
    'idfc blackbear',
    'bad vibes forever XXXTENTACION',
    'STILL CHOSE YOU (feat. Mustard) The Kid LAROI',
    'Maniac Conan Gray',
    'VIBEZ DaBaby',
    "We're Good Dua Lipa",
    'Whistle Flo Rida',
    'Manike Mage Hithe Chamath Sangeeth',
    'Liggi Ritviz',
    'Riha Anuv Jain',
    'Someone You Like The Girl and The Dreamcatcher',
    'Hosanna Hillsong Worship',
    'Hold On To Me Lauren Daigle',
    'Overdrive Conan Gray',
    'Strawberries & Cigarettes Troye Sivan',
    'Overwhelmed (Ryan Mack Remix) Ryan Mack',
    "I'm not Pretty JESSIA",
    'overwhelmed Royal & the Serpent',
    'Mad at Disney salem ilese',
    "Fallin’ (Adrenaline) Why Don't We",
    'Welcome to Wonderland Anson Seabra',
    'Freaks Jordan Clarke',
    'Psycho Maisie Peters',
    'everything sucks vaultboy',
    'The Way You Felt Alec Benjamin',
    "Guess That's Love Ryan Mack",
    'Funny Story Cate',
    'Don’t Give Up On Me Andy Grammer',
    'Broke Ryan Mack',
    'CHICKEN TENDIES Clinton Kane',
    'fairytales Gabby Sophia',
    'Aadmi Chutiya Hai Rahgir',
    'Pran Ritviz',
    'WAP Zane Hijazi',
    'O.D.D. Hey Violet',
    'Pal Behta Jaaye Vismay Patel',
    'Hoodie Hey Violet',
    'Sorry That I Do That Anna Clendening',
    'The Last Goodbye The Kills',
    'I Need Some Sleep Eels',
    'Tohfa Vayu',
    'If You’re Gonna Leave - Bvrnout Remix PLVTINUM',
    'Weak AJR',
    'Fall With Me Aaron Doh',
    'Bang! AJR',
    'Come My Way PLVTINUM',
    'Friendly Neighborhood Poltergeist Rory Webley',
    'Boom Zane Hijazi',
    'Idk Bruce Wiegner',
    'Spicy (feat. Post Malone) Ty Dolla $ign',
    'emotions iann dior',
    'Hard Work Pays Off Future',
    'ROCKSTAR (feat. Roddy Ricch) DaBaby',
    'Love Yourz J. Cole',
    'Woah Lil Baby',
    'Let Me Down Slowly / Main Dhoondne Ko Zamaane (Medley) Abstract Cartoons',
    'Habits of My Heart - EP Version Jaymes Young',
    'All Good Things (Come To An End) Nelly Furtado',
    'Each Coming Night Iron & Wine',
    'Beige Yoke Lore',
    'Rosyln Bon Iver',
    'Unconditionally Katy Perry',
    'You Are The Reason Calum Scott',
    'Sad Song (feat. Elena Coats) We The Kings',
    'Run to You Lea Michele',
    'One Call Away Charlie Puth',
    'When I Was Your Man Bruno Mars',
    'Little Do You Know Alex & Sierra',
    'Someone You Loved Lewis Capaldi',
    'the words Christina Perri',
    'Gone, Gone, Gone Phillip Phillips',
    "We Don't Talk Anymore (feat. Selena Gomez) Charlie Puth",
    'Heart By Heart Demi Lovato',
    'Just the Way You Are Bruno Mars',
    'Flashlight - From "Pitch Perfect 2" Soundtrack Jessie J',
    'The Music Kideko',
    'All of Me John Legend',
    'human Christina Perri',
    'Say Something A Great Big World',
    'The One That Got Away Katy Perry',
    'Love Me Like You Do - From "Fifty Shades Of Grey" Ellie Goulding',
    'Everything I Need Skylar Grey',
    'Set Fire to the Rain Adele',
    "Say You Won't Let Go James Arthur",
    'You & I One Direction',
    'Surrender Natalie Taylor',
    'Not About Angels Birdy',
    'Little Talks Of Monsters and Men',
    'We Are Young (feat. Janelle Monáe) fun.',
    'Somebody That I Used To Know - 4FRNT Remix Gotye',
    'Sweet but Psycho Ava Max',
    'wannabe renforshort',
    'Dandelion Gabbie Hanna',
    'do re mi blackbear',
    'Selfish Love (with Selena Gomez) - Tiësto Remix DJ Snake',
    'Come & Get It Selena Gomez',
    'Vulnerable Selena Gomez',
    'Boyfriend Selena Gomez',
    'Rare Selena Gomez',
    'People You Know Selena Gomez',
    'Round & Round Selena Gomez & The Scene',
    'I Can’t Get Enough (benny blanco, Selena Gomez, J Balvin, Tainy) benny blanco',
    'She Selena Gomez',
    'Love Will Remember Selena Gomez',
    'Wolves Selena Gomez',
    'Only You Selena Gomez',
    'Hands To Myself Selena Gomez',
    'Fetish (feat. Gucci Mane) Selena Gomez',
    'Taki Taki (with Selena Gomez, Ozuna & Cardi B) DJ Snake',
    '@ my worst blackbear',
    'Stupid Feelings 220 KID',
    'Better Days Dermot Kennedy',
    'papercuts Machine Gun Kelly',
    'Walking Away Chelsea Cutler',
    'Love Runs Out (feat. G-Eazy & Sasha Alex Sloan) Martin Garrix',
    'INDUSTRY BABY (feat. Jack Harlow) Lil Nas X',
    'SHUM Go_A',
    'Pure Water (with Migos) Mustard',
    'Legendary (feat. Gunna) Tyga',
    'Gang Up (with Young Thug, 2 Chainz & Wiz Khalifa feat. PnB Rock) Young Thug',
    'I Know You so Well Sarah Meow',
    'Rumors (feat. Cardi B) Lizzo',
    'Take My Breath The Weeknd',
    "Beggin' Måneskin",
    'Happier Than Ever Billie Eilish',
    '2055 Sleepy Hallow',
    "Don't Go Yet Camila Cabello",
    'Pepas Farruko',
    'traitor Olivia Rodrigo',
    'I WANNA BE YOUR SLAVE Måneskin',
    'Skate Bruno Mars',
    'Woman Doja Cat',
    'Volví Aventura',
    'Love Tonight - Edit Shouse',
    'Motley Crew Post Malone',
    'Permission to Dance BTS',
    'Todo De Ti Rauw Alejandro',
    'Chosen (feat. Ty Dolla $ign) Blxst',
    'Just for me PinkPantheress',
    'HALF HEARTED We Three',
    'Fall Eminem',
    'Darkness Eminem',
    'Lucky You (feat. Joyner Lucas) Eminem',
    'Paul - Skit Paul Rosenberg',
    'Greatest Eminem',
    'Venom - Music From The Motion Picture Eminem',
    'Hanuman Chalisa Shankar Mahadevan',
    'Shree Hanuman Chalisa Hariharan',
    "Shekhar Ravjiani's Hanuman Chalisa Shekhar Ravjiani",
    'Shiv Tandav Stotram Shankar Mahadevan',
    'Ae Watan (Male) Arijit Singh',
    'Challa Romy',
    'Lose Yourself - From "8 Mile" Soundtrack Eminem',
    'Gnat Eminem',
    'Rap God Eminem',
    'Godzilla (feat. Juice WRLD) Eminem',
    'River (feat. Ed Sheeran) Eminem',
    'The Ringer Eminem',
    'Mockingbird Eminem',
    'Killshot Eminem',
    'The Monster Eminem',
    'Soldier NEFFEX',
    'Ghost Of You 5 Seconds of Summer',
    'One More Dance (with Alida) R3HAB',
    "Feelin' U Kelli-Leigh",
    'Chun-Li Nicki Minaj',
    'Bummerland AJR',
    'All Time Low Jon Bellion',
    'Keep You Safe SHRK',
    'Roses SAINt JHN',
    'Alright (feat. Trippie Redd & Preme) Wiz Khalifa',
    'Way Out (feat. Big Sean) Jack Harlow',
    'THINK ABOUT ME jxdn',
    'Girls Have Fun (feat. G-Eazy & Rich The Kid) Tyga',
    'What You Know Bout Love Pop Smoke',
    'for mah girl LUUV.',
    'By Your Side (feat. Tom Grennan) - Oliver Heldens Remix Calvin Harris',
    "'Till I Collapse Eminem",
    'Main Dhoondne Ko Zamaane Mein (From "Heartless") Arijit Singh',
    'The Imitation Game Alexandre Desplat',
    'Time Hans Zimmer',
    'Light of the Seven Ramin Djawadi',
    'Astronaut In The Ocean Masked Wolf',
    '24 (feat. Lil Baby) Money Man',
    'OUT WEST (feat. Young Thug) JACKBOYS',
    'Lie NF',
    'Dirty Dancer Enrique Iglesias',
    'Sometimes DallasK',
    'Push & Pull Georgia Webster',
    'She Gets the Flowers Beth McCarthy',
    "Never Be Lonely Gigi D'Agostino",
    'Through The Storm Don Diablo',
    'Sweater Weather The Neighbourhood',
    'See You Again (feat. Charlie Puth) Wiz Khalifa',
    'Daddy Issues The Neighbourhood',
    'XO EDEN',
    'Chandelier Sia',
    'I Want You To Know Zedd',
    'Tick Tock (feat. 24kGoldn) Clean Bandit',
    "Life's A Mess (feat. Halsey) Juice WRLD",
    'Legends Juice WRLD',
    "Hollywood's Bleeding Post Malone",
    'Change My Clothes Dream',
    'Hurricane Kanye West',
    'Donda Chant Kanye West',
    'Jail Kanye West',
    'Donda Kanye West',
    'Close Your Eyes - Spotify Singles LP Giobbi',
    'Stay A Little Longer Anushka Shahaney',
    'older Nightly',
    'Jesus Lord pt 2 Kanye West',
    'Believe What I Say Kanye West',
    'Butterflies GASHI',
    'Roses GASHI',
    'Better Days Arman Cekin',
    'Reasons COTIS',
    'NIGHTRIDER Arizona Zervas',
    'TLC Sy Ari Da Kid',
    'No Promises (feat. Demi Lovato) Cheat Codes',
    'rockstar (feat. 21 Savage) Post Malone',
    'Congratulations Post Malone',
    'Better Now Post Malone',
    'Only Wanna Be With You - Pokémon 25 Version Post Malone',
    'Hold On Chord Overstreet',
    'Tattoo Jordin Sparks',
    'Bad Habits - Acoustic Version Ed Sheeran',
    'Addict Of Magic Picture This',
    'You should be sad Halsey',
    'Psycho (feat. Ty Dolla $ign) Post Malone',
    'Not Afraid Eminem',
    'exile Taylor Swift',
    "my ex's best friend (with blackbear) Machine Gun Kelly",
    'exile (feat. Bon Iver) - the long pond studio sessions Taylor Swift',
    'Is It Just Me? (feat. Charlie Puth) Sasha Alex Sloan',
    'Getaway Car Taylor Swift',
    'Feel FLETCHER',
    'Dancing With Your Ghost Sasha Alex Sloan',
    'Tightrope ZAYN',
    'Liability Lorde',
    'willow Taylor Swift',
    'Walked Through Hell Anson Seabra',
    'could cry just thinkin about you - Full Version Troye Sivan',
    'Toxic AP Dhillon',
    'Insane AP Dhillon',
    'Nit Nit Jasleen Royal',
    'Saint-Tropez Post Malone',
    "Can't Be Touched (feat. Mr. Magic & Trouble) Roy Jones Jr.",
    'Superman Eminem',
    'RAP DEVIL Machine Gun Kelly',
    'Warm Up NF',
    'Numb / Encore JAY-Z',
    'Remember the Name (feat. Styles of Beyond) Fort Minor',
    'Remember The Name (feat. Eminem & 50 Cent) Ed Sheeran',
    'Space Bound Eminem',
    'We Own It (Fast & Furious) 2 Chainz',
    'Purple Lamborghini (with Rick Ross) Skrillex',
    'Broken Lund',
    'Waiting Vicetone',
    'Hurts Sometimes (with Jonathan Mendelsohn) SLANDER',
    "Didn't I OneRepublic",
    'Youngblood 5 Seconds of Summer',
    "don't say you love me joan",
    'Just For Me (with SZA) - Space Jam: A New Legacy SAINt JHN',
    'Or Nah (feat. The Weeknd, Wiz Khalifa & DJ Mustard) - Remix Ty Dolla $ign',
    'Violent carolesdaughter',
    "don't fall 44phantom",
    'the way that you see me (feat. Ayleen Valentine) Powfu',
    'say goodbye Sarcastic Sounds',
    "Can't Trust A Soul 7ru7h",
    'Me and You Cold Hart',
    'Waka Waka (This Time for Africa) [The Official 2010 FIFA World Cup (TM) Song] (feat. Freshlyground) Shakira',
    'Secrets LUM!X',
    'Girls Want Girls (with Lil Baby) Drake',
    'Apricots MAY-A',
    'the long way home (feat. Sara Kays & Sarcastic Sounds) Powfu',
    'Thot Shit Megan Thee Stallion',
    'Old Friends Scott Helman',
    'What If I Told You That I Love You Ali Gatie',
    'Hide and Seek Lizz Robinett',
    'Rockstar Josh Golden',
    '10,000 Hours (with Justin Bieber) Dan + Shay',
    "I Don't Care (with Justin Bieber) Ed Sheeran",
    'Lose You To Love Me Selena Gomez',
    'Here With Me Marshmello',
    'The Middle Zedd',
    'Girls Like You Maroon 5',
    "Unbelievable Why Don't We",
    'Easier 5 Seconds of Summer',
    'Blank Space Taylor Swift',
    'Post Malone (feat. RANI) Sam Feldt',
    'Million Ways HRVY',
    "Fallin' All In You Shawn Mendes",
    'Lie To Me (feat. Julia Michaels) 5 Seconds of Summer',
    "fuck, i'm lonely (with Anne-Marie) Lauv",
    'Jocelyn Flores XXXTENTACION',
    'XO Tour Llif3 Lil Uzi Vert',
    '4 Da Gang (with Roddy Ricch) 42 Dugg',
    'Walk Down FNF Chop',
    "They Ain't You Tyla Yaweh",
    'No I in Team Arizona Zervas',
    'Tip Toe (feat. A Boogie Wit da Hoodie) Roddy Ricch',
    'Tyler Herro Jack Harlow',
    'The Scientist Tyler Ward',
    'The Scientist Corinne Bailey Rae',
    'Iris Kina Grannis',
    'Ugly Sugababes',
    'Try P!nk',
    'Apologize Timbaland',
    "She Doesn't Mind Sean Paul",
    'Got 2 Luv U (feat. Alexis Jordan) Sean Paul',
    'White Flag Dido',
    'Underwater MIKA',
    'Everytime Britney Spears',
    'Because of You Kelly Clarkson',
    'Relax, Take It Easy MIKA',
    'All Good Things (Come To An End) - Spanish Version Nelly Furtado',
    'Bleeding Love - Radio Edit Leona Lewis',
    'Umbrella - Radio Edit Rihanna',
    'Say It Right Nelly Furtado',
    'Torn Natalie Imbruglia',
    'POPSTAR (feat. Drake) DJ Khaled',
    'GREECE (feat. Drake) DJ Khaled',
    'LET IT GO (feat. Justin Bieber & 21 Savage) DJ Khaled',
    'Lightskin Lil Wayne Tyga',
    'Life Is Good (feat. Drake) Future',
    'Whats Poppin (feat. DaBaby, Tory Lanez & Lil Wayne) [Remix] - Bonus Track Jack Harlow',
    'Roses - Imanbek Remix [Latino Gang] SAINt JHN',
    'I Won Ty Dolla $ign',
    'His & Hers (feat. Don Toliver, Lil Uzi Vert & Gunna) Internet Money',
    'Move Ya Hips (feat. Nicki Minaj & MadeinTYO) A$AP Ferg',
    'Thrusting (feat. Swae Lee & Future) Internet Money',
    'Lemonade - Remix Internet Money',
    'Goddamn (feat. A Boogie wit da Hoodie) Tyga',
    'Moana G-Eazy',
    'Turks (with Gunna & ft. Travis Scott) NAV',
    'All the Smoke (feat. Gunna & Wiz Khalifa) Tyla Yaweh',
    'Baby (Lil Baby feat. DaBaby) Quality Control',
    'Plain Jane REMIX (feat. Nicki Minaj) A$AP Ferg',
    'Tommy Lee (feat. SAINt JHN & Post Malone) - Remix Tyla Yaweh',
    'No Brainer (feat. Justin Bieber, Chance the Rapper & Quavo) DJ Khaled',
    'Ric Flair Drip (& Metro Boomin) Offset',
    'Racks 2 Skinny Migos',
    'Still Wiz Wiz Khalifa',
    'High Right Now (feat. Wiz Khalifa) - Remix Tyla Yaweh',
    'I DID IT (feat. Post Malone, Megan Thee Stallion, Lil Baby & DaBaby) DJ Khaled',
    'Jealous (feat. Chris Brown, Lil Wayne & Big Sean) DJ Khaled',
    'Used To Be - Rasster Remix GASHI',
    'I WANNA SEE SOME ASS (feat. jetsonmade) Jack Harlow',
    'Tryna F**k Me (feat. Post Malone) Lloyd Banks',
    'Way down We Go KALEO',
    'Sorry Matt Haughey',
]

const songsName = [
    'Saiyaan Ji',
    'Falling',
    'Shayad',
    'Malang (Title Track) [From "Malang - Unleash The Madness"]',
    'Genda Phool (feat. Payal Dev)',
    'Humraah (From "Malang - Unleash The Madness")',
    'Baila Conmigo (with Rauw Alejandro)',
    'You (with Marshmello & Vance Joy)',
    'Higher (feat. iann dior)',
    'Element',
    'HUMBLE.',
    'Sucker for Pain (with Wiz Khalifa, Imagine Dragons, Logic & Ty Dolla $ign feat. X Ambassadors)',
    'Dip (feat. Nicki Minaj) (feat. Nicki Minaj)',
    'goosebumps',
    'Walk It Talk It',
    'King Kunta',
    'Swang',
    "I'm the One (feat. Justin Bieber, Quavo, Chance the Rapper & Lil Wayne)",
    'Another Love',
    'People Help the People',
    'unravel (acoustic version) - Acoustic Version',
    'Isabella\'s Lullaby (from "The Promised Neverland")',
    'asphyxia',
    'Kokoronashi',
    "Can't Hold Us - feat. Ray Dalton",
    'Somebody That I Used To Know',
    'River Flows In You',
    "Comptine d'un autre été, l'après-midi",
    'You Raise Me Up',
    'Hope',
    'Close To Me',
    'Baarishein',
    'Why Did I Answer?',
    'Baari',
    'Big Gangsta',
    "Famous (I'm The One) (feat. Yo Gotti & DeJ Loaf)",
    'Beware',
    'The Thrill',
    'Dior',
    'good 4 u',
    'Kiss Me More (feat. SZA)',
    'Butter',
    'MONTERO (Call Me By Your Name)',
    'Arcade',
    'WITHOUT YOU',
    'Leave The Door Open',
    'Levitating (feat. DaBaby)',
    'Peaches (feat. Daniel Caesar & Giveon)',
    'Save Your Tears (with Ariana Grande) (Remix)',
    'deja vu',
    'Beautiful Mistakes (feat. Megan Thee Stallion)',
    "Sygrayem (Let's Play)",
    'Our Song',
    'Leave Before You Love Me (with Jonas Brothers)',
    'Build a Bitch',
    'Heartbreak Anthem (with David Guetta & Little Mix)',
    'unravel',
    'ブルーバード',
    'Lucid Dreams',
    'Experience',
    'Hello (feat. A Boogie Wit da Hoodie)',
    'Deep End Freestyle',
    'Gang Shit No Lame Shit',
    'Sideways',
    'Nightlight',
    'Night Changes',
    'Alive',
    'A Thousand Years',
    "I Know It's You",
    'A Thousand Years (feat. Steve Kazee) - Pt. 2; The Twilight Saga: Breaking Dawn Soundtrack',
    'Main Title',
    "Beth's Story",
    'Methuen Home For Children 1957',
    "The Scholar's Mate",
    "You're Gloating",
    'Training With Mr. Schaibel',
    'Mishri',
    'SugarCrash!',
    'Higher Power',
    'Break My Heart Myself (feat. Travis Barker)',
    'Echo (with KSHMR)',
    'Astronomy',
    'Alag Aasmaan',
    'Sau Aasmaan',
    'Besabriyaan',
    'What If (I Told You I Like You)',
    'Everybody Wants You',
    'Two of Us',
    'Wonder',
    'Before You Go',
    'A Whole New World (End Title) - From "Aladdin"',
    'Just Like You',
    'What A Time (feat. Niall Horan)',
    'Interstellar Main Theme - Piano Version',
    'Interstellar- Main Theme',
    'Without Me (with Juice WRLD)',
    'Without Me',
    'you broke me first',
    'Jalebi Baby',
    'Switch It Up (feat. sokodomo) - Prod. Cha Cha Malone',
    'Mera Mann Kehne Laga',
    'Good Years',
    'Grenade',
    'Talking to the Moon',
    'My Heart Will Go On - Love Theme from "Titanic"',
    'Stereo Hearts (feat. Adam Levine)',
    'Stereo Love',
    'Righteous',
    '734',
    "Life's A Mess II (with Clever & Post Malone)",
    'Lucid Dreams (feat. Lil Uzi Vert) - Remix',
    'Come & Go (with Marshmello)',
    'Blastoff (feat. Juice Wrld & Trippie Redd)',
    'Stay High',
    'Bandit (with YoungBoy Never Broke Again)',
    'No Me Ame',
    'One Dance',
    'Lean On',
    'Sunflower - Spider-Man: Into the Spider-Verse',
    'Rolling in the Deep',
    '7 rings',
    'Wake Me Up',
    'Love The Way You Lie',
    'Morning',
    'I Should Quit',
    'Am I Good Enough Now?',
    'u love u (with Tate McRae)',
    'By Your Side (feat. Tom Grennan)',
    'Lost Cause',
    'seaside_demo',
    'Last Train Home',
    't r a n s p a r e n t s o u l feat. Travis Barker',
    'Shape of You',
    'bad guy',
    'Rather Be (feat. Jess Glynne)',
    'Cocaine',
    'Honesty',
    'Mask Off',
    'Mask Off - Marshmello Remix',
    'Hymn for the Weekend - Seeb Remix',
    'The Scientist',
    'My Way',
    'All Night',
    'I Don’t Wanna Live Forever (Fifty Shades Darker)',
    'Let Me Love You',
    'Adventure of a Lifetime',
    'This Is What You Came For (feat. Rihanna)',
    'Perfect Strangers',
    'Perfect',
    'Jalebi Baby (Tesher x Jason Derulo)',
    'Love Again',
    'Hide (feat. Seezyn)',
    'Disrespectful',
    'Crooked Smile (feat. TLC)',
    'Into Your Arms (feat. Ava Max)',
    'Into Your Arms (feat. Ava Max) - BEAUZ Remix',
    'anxiety (with FRND)',
    'Good Things Fall Apart vs. Sad Songs (With Said The Sky feat. Annika Wells)',
    'If You Love Her',
    'Take Me To Church',
    'Takeaway',
    'Call You Mine',
    "If I Can't Have You",
    'Lily',
    'Teeth',
    'Hate Me',
    'Better Days',
    'Do You Mean',
    'Want You Back',
    'One More Day (with Chandler Leighton)',
    'In the End',
    'Believer',
    'Radioactive',
    'Centuries',
    'Hall of Fame (feat. will.i.am)',
    'Animals',
    'Tchaikovsky: Swan Lake, Op. 20, Act 2: Scene (Moderato)',
    'Hero (feat. Christina Perri)',
    'Goodbye To A World',
    'Magic in the Air (feat. Ahmed Chawki)',
    'telepatía',
    'E-ER (feat. Lil Yachty)',
    'Ex Bitch',
    'Ga$ Money',
    'Yonaguni',
    'Need To Know',
    'The Business',
    'Tokyo Drift',
    'Wants and Needs (feat. Lil Baby)',
    'RAPSTAR',
    'Look Back at It',
    'Can We Kiss Forever?',
    'Kiss Me Thru The Phone',
    'Closer',
    'Something Just Like This',
    "Don't Let Me Down",
    'This Feeling',
    'Who Do You Love',
    'Roses',
    'Paris',
    'Sick Boy',
    'The Reaper',
    'Family',
    'Share',
    'Tell Me U Luv Me (with Trippie Redd)',
    'Hide Away',
    'One Moment in Time - Remastered',
    'Lost',
    'EveryTime I Cry',
    'Fingers Crossed',
    'Cloudy Day',
    'Imagine - Tiësto Remix',
    'Lose Somebody',
    'Going Dumb',
    'Silence',
    "I'm a Mess",
    'Alone, Pt. II',
    'Selfish Love (with Selena Gomez)',
    'Symphony (feat. Zara Larsson)',
    'Gone Are The Days (feat. James Gillespie)',
    'Midnight (feat. Liam Payne)',
    'More Than You Know',
    'The Best Days (feat. Tabitha)',
    'Lonely (with benny blanco)',
    'Drag Me Down',
    'Lose My Mind',
    'Body Back (feat. Maia Wright) - Deniz Koyu Remix',
    'Think About You - Galantis Remix',
    'No Money',
    'Playing Mr. Ganz',
    'Ceiling Games',
    'First Day At School',
    'The Green Pills',
    'Kentucky State Championship 1963',
    'Top Boards',
    'Playing Townes',
    'Playing Beltik',
    'The Lake - Cincinnati',
    'Playing Benny - Las Vegas 1966',
    'Two Sides Of The Same Coin',
    'Mexico City Invitational 1966',
    'Playing Girev I',
    'Playing Girev II',
    'Borgov I',
    'Beth Alone',
    'Ohio US Championship 1967',
    'New York',
    'Training With Benny',
    'Paris Tournament 1967',
    'Borgov II',
    'Jolene!',
    'Returning To Methuen',
    'Turning Point',
    'USSR',
    'Moscow Invitational 1968',
    'Close Your Eyes',
    'Borgov III',
    'The Final Game',
    "Take It, It's Yours",
    'By Your Side',
    'Throwback',
    '2 Hearts (feat. Gia Koka)',
    'Hear Me Say',
    'Speechless (feat. Erika Sirola) - MOTi Remix',
    'Higher (feat. iann dior) - Dimitri Vegas & Like Mike Remix',
    'Dandelions',
    'Too Late (feat. Wiz Khalifa & Lukas Graham) - Riggi & Piros Remix',
    'Space Melody (Edward Artemyev) (feat. Leony)',
    'Another Life (feat. Alida)',
    'Way Back Home (feat. Conor Maynard) - Sam Feldt Edit',
    'Faded - Luke Christopher Remix',
    'Without You',
    'Be Kind (with Halsey)',
    'Cheerleader - Felix Jaehn Remix Radio Edit',
    'Daylight',
    'All We Need (feat. Shy Girls) - Dzeko & Torres Remix Radio Edit',
    'SOS (feat. Aloe Blacc)',
    'Hearts on Fire - CORSAK & Willim Remix',
    'You Know You Like It',
    'Fast Car',
    'Sixteen',
    'In the Name of Love',
    'Sweet Dreams',
    'Summer Thing',
    'Whole Life',
    "Don't Wanna Fall",
    'Excitement (feat. PARTYNEXTDOOR)',
    'Body (Remix) [feat. ArrDee, E1 (3x3), ZT (3x3), Bugzy Malone, Buni, Fivio Foreign & Darkoo]',
    'Stressed Out',
    'Beauty and the Beast - from the Soundtrack "Beauty and the Beast"',
    'Another Love - Radio Edit',
    'working',
    'Reckless',
    'Solar Power',
    'cold/mess',
    'Kho Gaye Hum Kahan',
    "i don't want to watch the world end with someone else",
    'Knock Knock',
    'Hula Hoop',
    'Pasadena',
    'Feel Something',
    "Nothing's the Same",
    'You Should Run',
    'Poison',
    'DRXGS - Rawtek Remix',
    'Shade of Yellow',
    'Black Hole',
    'FEFE',
    'Magic',
    'Look at the Sky',
    'So What (feat. A R I Z O N A)',
    'Taste of You (feat. Dove Cameron)',
    'Deep Blue',
    'Gasoline (feat. Laura White)',
    'In Your Arms (with X Ambassadors)',
    'WOW (with Emma Steinbakken)',
    'Shut The World Out',
    'Moon Rider (feat. Wrabel)',
    'I Love You.',
    'Good Things Fall Apart (with Jon Bellion)',
    'UCLA',
    'The Bender (with Brando)',
    'Sweet Time',
    'Big Love (with EARTHGANG & MNDR)',
    'Someone To You',
    'Dernière Danse',
    'Summer Air',
    'Impossible',
    'Get Together',
    'Enjoy Enjaami - Spotify Singles (with Dhee feat. Arivu & Santhosh Narayanan)',
    'Weekend Vibe (feat. Desi Crew)',
    'YUSO (feat. Lil Wayne & Saweetie)',
    'Wolves (feat. Post Malone)',
    'New Love (feat. Ellie Goulding)',
    'My House - Chill Mix',
    'Slow Clap (with Saweetie)',
    'Glad You Came',
    'Smile (with The Weeknd)',
    'Wishing Well',
    'Real Shit (with benny blanco)',
    'Shots',
    'Stitches',
    "There's Nothing Holdin' Me Back",
    'Lost In Japan',
    'Treat You Better',
    'Señorita - Slowed + Reverb',
    'Señorita',
    'Real Love',
    'Beside You (feat. Georgia Ku)',
    "Don't Wanna Know - Ryan Riback Remix",
    "We're Coming Up",
    'Floating Through Space',
    'In My Blood',
    'Memories',
    'Imagination',
    'Rescue Me',
    'How Do You Sleep?',
    'Rewrite The Stars',
    'Dusk Till Dawn (feat. Sia) - Radio Edit',
    'ME! (feat. Brendon Urie of Panic! At The Disco)',
    'Love Me Like You Do',
    "It's You",
    'Break My Heart',
    'Beautiful People (feat. Khalid)',
    'Liar',
    'Sucker',
    'Cheating on You',
    'Back To You - From 13 Reasons Why – Season 2 Soundtrack',
    'Happier',
    'So Am I (feat. NCT 127)',
    'Personal',
    'That Girl',
    'Woman Like Me (feat. Nicki Minaj)',
    'Best Part of Me (feat. YEBBA)',
    'Watermelon Sugar',
    'Sing It With Me',
    "If I Can't Have You - Gryffin Remix",
    'Looking at Me',
    'I Got You - Cheat Codes Remix',
    'Choo Lo',
    'Dil Mere',
    'Aaftaab',
    'Aaoge Tum Kabhi',
    'Khudi',
    'Dilnawaz',
    'Kaisey Jiyun',
    'Mizaaj',
    'Mere Yaar',
    'Solo (feat. Demi Lovato)',
    'Say My Name',
    "We Don't Care",
    'Without You (feat. Sandro Cavazza)',
    'Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)',
    '2002',
    'Rewrite The Stars (with James Arthur & Anne-Marie)',
    'Girls Like You (feat. Cardi B) - Cardi B Version',
    'Happy Now',
    'No Lie',
    'Just My Type',
    'Lonely Together (feat. Rita Ora)',
    'I Like Me Better',
    'Timber (feat. Ke$ha)',
    'Black Mask (feat. Pop Smoke)',
    'Chain My Heart',
    'Eastside (with Halsey & Khalid)',
    'Sky',
    'Bad Habits',
    "I Don't Do Drugs (feat. Ariana Grande)",
    '18',
    'You Right',
    'dancing in the kitchen',
    'Let Me Know',
    'Funny',
    'BED',
    'No Chill (feat. Lil Xxel)',
    'Unfamiliar',
    'Feels',
    'Demons',
    'Pavane, Op. 50',
    'Merry-Go-Round(人生のメリーゴーランド)',
    'Scheherazade: The Tale of the Kalendar Prince',
    'Masquerade (Suite): 1. Waltz - Excerpt',
    'Violin Concerto in D Major, Op. posth., No. 2: Adagio',
    'I Want It That Way',
    'Aicha',
    'Flightless Bird, American Mouth',
    'A Sky Full of Stars',
    'Renegades',
    'Maps',
    'Shots - Broiler Remix',
    'Ode To My Family',
    'Zombie',
    'Linger',
    'In Cold Light (Alexandra Hamilton-Ayres Rework)',
    'Back To The Sky',
    'Wandering II - Ed Carlsen Rework',
    'Retour',
    'Mere Rashke Qamar (From "Baadshaho")',
    "I Don't Know Why",
    'Break Me Down',
    'On My Life',
    'Round and Round',
    'Let You Know',
    'Strong',
    'Ghalat Fehmi - From "Superstar"',
    'Tera Ghata',
    'Titans (feat. Sia & Labrinth) - Imanbek Remix',
    'Hero',
    'Aakhri Salaam',
    'Yeh Zindagi Hai',
    'Bandey',
    'All I Wanna Do',
    'Even When/The Best Part - From "High School Musical: The Musical: The Series (Season 2)"',
    'Run',
    'Your Power',
    'Electric - Pokemon 25 Version',
    'FUCKBOY',
    'drivers license',
    "Don't Start Now",
    'Anyone',
    'Monster (Shawn Mendes & Justin Bieber)',
    'Goodbye',
    'The Rose Song - From "High School Musical: The Musical: The Series (Season 2)"',
    'exile (feat. Bon Iver)',
    'Death By A Thousand Cuts - Live From Paris',
    'Look What You Made Me Do',
    'long story short',
    'closure',
    'Fifteen',
    'Sexy Bitch (feat. Akon)',
    'Party Rock Anthem',
    'New Thang',
    'Counting Stars',
    'Feel Good (feat. Daya)',
    '2U (feat. Justin Bieber)',
    'Pretty Please',
    'Fractures',
    'Galway Girl',
    'Locked Away (feat. Adam Levine)',
    'Show Me Love',
    'Let You Down',
    'Kiss and Make Up',
    'Sweet Harmony',
    'Talk To Me (feat. Conor Maynard & RANI) - Sam Feldt Edit',
    'Arcade (feat. FLETCHER)',
    'Revolver',
    'All Too Well',
    'Die For a Man (feat. Lil Uzi Vert)',
    'Telling Myself',
    'I Would Like - R3hab Remix',
    'Diamonds',
    'Agar Tum Saath Ho',
    'Agar Tum Mil Jao',
    "I'm Not Mad",
    'Main Rahoon Ya Na Rahoon',
    'Scars To Your Beautiful',
    'IDK You Yet',
    'A Little Bit Yours',
    'Everyone Changes',
    'Bad boy',
    'Ransom (with Juice WRLD) - Remix',
    'Startender (feat. Offset and Tyga)',
    'Fire On Fire',
    'Neighbor (feat. Travis Scott)',
    'One More Time (feat. Alida) - Klingande Remix',
    'Talk',
    "Can't Go Home (feat. Adam Lambert) - Radio Edit",
    '(They Long To Be) Close To You',
    "We Don't Talk Anymore (feat. Selena Gomez) - Attom Remix",
    'Worship',
    'Jar of Hearts',
    'Echo (feat. blackbear)',
    'Sometimes',
    'Spirits',
    "This One's for You (feat. Zara Larsson) (Official Song UEFA EURO 2016)",
    'Love Yourself',
    'Play Hard (feat. Ne-Yo & Akon) - New Edit',
    'Shallow',
    'Heathens',
    'You And Me',
    'Mine',
    'In The Name Of Love - The Him Remix',
    'Nobody',
    'Big Plans',
    'Train Wreck',
    'My House',
    'Secrets',
    '1-800-273-8255',
    'DRXGS',
    'All Time Low',
    'Real Friends',
    'She Said',
    'die without u',
    'New Rules',
    'Stranger',
    'im all alone',
    'Spin The Block (feat. Future)',
    'detest me',
    'Runaway',
    'BedRock',
    "Buy U a Drank (Shawty Snappin') (feat. Yung Joc)",
    'Heat Waves',
    'Let Them Know',
    'Our World (feat. Daniele Sorrentino)',
    'Scared to Be Lonely',
    "It Ain't Me (with Selena Gomez)",
    'Mama',
    'Faded',
    'Heather',
    'At My Worst',
    'Mood (feat. iann dior)',
    'Hold On',
    'Hate Me (with Juice WRLD)',
    'Circles',
    'Signal',
    "The Blower's Daughter",
    "i'm so tired...",
    'Met Him Last Night - Dave Audé Remix',
    'Freaks',
    'Cold Light',
    'Just Dance',
    'Lift Your Energy',
    'Payphone',
    'Seasons - NIVIRO Remix',
    'S&M Remix',
    'Blinding Lights',
    'Umbrella',
    'Cold Skin',
    'Better Not (with Wafia)',
    'I Get You',
    'Line Of Sight (Reprise) (feat. WYNNE & Mansionair)',
    'Only One I Need',
    'All Eyes On Me',
    'STAY (with Justin Bieber)',
    'Just A Mess',
    'Renegade (feat. Taylor Swift)',
    'Demeanor (feat. Dua Lipa)',
    'Good Life (with G-Eazy & Kehlani)',
    'Bamboléo',
    'Feel This Moment (feat. Christina Aguilera)',
    "Don't Leave Me Now",
    'Sleepover',
    'All My Friends',
    'Not Allowed',
    'Brush Fire',
    'Butterflies',
    'Shower',
    'Emptiness',
    'If I Could',
    'Bright Eyes',
    'Game of Thrones - Theme',
    'People Watching',
    'The Rains of Castamere',
    'The Rains of Castamere (From the HBO® Series Game Of Thrones - Season 4)',
    'The Rains Of Castomere',
    'Forever',
    'Power is Power (feat. The Weeknd & Travis Scott)',
    'All I Want (Floorplan Remix) [Extended Mix] (feat. Andrea Martin)',
    "What's Up",
    'When I Need You',
    'Beautiful Now',
    "Won't Bite (feat. Smino)",
    "She's My Collar (feat. Kali Uchis)",
    'Hold It Against Me',
    'I miss you, I’m sorry',
    'Fingers Crossed (with Julia Michaels)',
    'Mood (Remix) feat. Justin Bieber, J Balvin & iann dior',
    'NUMB',
    'Hate You + Love You (feat. AJ Mitchell)',
    'Party Girl',
    'Heart Attack',
    'Love Is Gone - Acoustic',
    'Home (with Machine Gun Kelly, X Ambassadors & Bebe Rexha)',
    'Changes',
    'Back To U',
    'Time',
    '7UP',
    'Hate The Way (feat. blackbear)',
    'lie to me',
    'Do You Believe',
    "i hate u, i love u (feat. olivia o'brien)",
    'ANGELS & DEMONS',
    "I Don't Want You Back",
    'Chasing_(Demo)',
    'hot girl bummer',
    'idfc - Tarro Remix',
    'Ridiculous Thoughts',
    'When We Were Young',
    'Human Spirit',
    'Pain - Remastered',
    'Send Me An Angel',
    'Under Your Spell',
    'Frozen',
    'Stay',
    'Bartholomew',
    'Loki Green Theme',
    'Photograph',
    'SAD!',
    'Everybody Dies In Their Nightmares',
    'Losing Interest',
    'Tory lanez freestyle ',
    'idfc',
    'bad vibes forever',
    'STILL CHOSE YOU (feat. Mustard)',
    'Maniac',
    'VIBEZ',
    "We're Good",
    'Whistle',
    'Manike Mage Hithe',
    'Liggi',
    'Riha',
    'Someone You Like',
    'Hosanna',
    'Hold On To Me',
    'Overdrive',
    'Strawberries & Cigarettes',
    'Overwhelmed (Ryan Mack Remix)',
    "I'm not Pretty",
    'overwhelmed',
    'Mad at Disney',
    'Fallin’ (Adrenaline)',
    'Welcome to Wonderland',
    'Psycho',
    'everything sucks',
    'The Way You Felt',
    "Guess That's Love",
    'Funny Story',
    'Don’t Give Up On Me',
    'Broke',
    'CHICKEN TENDIES',
    'fairytales',
    'Aadmi Chutiya Hai',
    'Pran',
    'WAP',
    'O.D.D.',
    'Pal Behta Jaaye',
    'Hoodie',
    'Sorry That I Do That',
    'The Last Goodbye',
    'I Need Some Sleep',
    'Tohfa',
    'If You’re Gonna Leave - Bvrnout Remix',
    'Weak',
    'Fall With Me',
    'Bang!',
    'Come My Way',
    'Friendly Neighborhood Poltergeist',
    'Boom',
    'Idk',
    'Spicy (feat. Post Malone)',
    'emotions',
    'Hard Work Pays Off',
    'ROCKSTAR (feat. Roddy Ricch)',
    'Love Yourz',
    'Woah',
    'Let Me Down Slowly / Main Dhoondne Ko Zamaane (Medley)',
    'Habits of My Heart - EP Version',
    'All Good Things (Come To An End)',
    'Each Coming Night',
    'Beige',
    'Rosyln',
    'Unconditionally',
    'You Are The Reason',
    'Sad Song (feat. Elena Coats)',
    'Run to You',
    'One Call Away',
    'When I Was Your Man',
    'Little Do You Know',
    'Someone You Loved',
    'the words',
    'Gone, Gone, Gone',
    "We Don't Talk Anymore (feat. Selena Gomez)",
    'Heart By Heart',
    'Just the Way You Are',
    'Flashlight - From "Pitch Perfect 2" Soundtrack',
    'The Music',
    'All of Me',
    'human',
    'Say Something',
    'The One That Got Away',
    'Love Me Like You Do - From "Fifty Shades Of Grey"',
    'Everything I Need',
    'Set Fire to the Rain',
    "Say You Won't Let Go",
    'You & I',
    'Surrender',
    'Not About Angels',
    'Little Talks',
    'We Are Young (feat. Janelle Monáe)',
    'Somebody That I Used To Know - 4FRNT Remix',
    'Sweet but Psycho',
    'wannabe',
    'Dandelion',
    'do re mi',
    'Selfish Love (with Selena Gomez) - Tiësto Remix',
    'Come & Get It',
    'Vulnerable',
    'Boyfriend',
    'Rare',
    'People You Know',
    'Round & Round',
    'I Can’t Get Enough (benny blanco, Selena Gomez, J Balvin, Tainy)',
    'She',
    'Love Will Remember',
    'Wolves',
    'Only You',
    'Hands To Myself',
    'Fetish (feat. Gucci Mane)',
    'Taki Taki (with Selena Gomez, Ozuna & Cardi B)',
    '@ my worst',
    'Stupid Feelings',
    'papercuts',
    'Walking Away',
    'Love Runs Out (feat. G-Eazy & Sasha Alex Sloan)',
    'INDUSTRY BABY (feat. Jack Harlow)',
    'SHUM',
    'Pure Water (with Migos)',
    'Legendary (feat. Gunna)',
    'Gang Up (with Young Thug, 2 Chainz & Wiz Khalifa feat. PnB Rock)',
    'I Know You so Well',
    'Rumors (feat. Cardi B)',
    'Take My Breath',
    "Beggin'",
    'Happier Than Ever',
    '2055',
    "Don't Go Yet",
    'Pepas',
    'traitor',
    'I WANNA BE YOUR SLAVE',
    'Skate',
    'Woman',
    'Volví',
    'Love Tonight - Edit',
    'Motley Crew',
    'Permission to Dance',
    'Todo De Ti',
    'Chosen (feat. Ty Dolla $ign)',
    'Just for me',
    'HALF HEARTED',
    'Fall',
    'Darkness',
    'Lucky You (feat. Joyner Lucas)',
    'Paul - Skit',
    'Greatest',
    'Venom - Music From The Motion Picture',
    'Hanuman Chalisa',
    'Shree Hanuman Chalisa',
    "Shekhar Ravjiani's Hanuman Chalisa",
    'Shiv Tandav Stotram',
    'Ae Watan (Male)',
    'Challa',
    'Lose Yourself - From "8 Mile" Soundtrack',
    'Gnat',
    'Rap God',
    'Godzilla (feat. Juice WRLD)',
    'River (feat. Ed Sheeran)',
    'The Ringer',
    'Mockingbird',
    'Killshot',
    'The Monster',
    'Soldier',
    'Ghost Of You',
    'One More Dance (with Alida)',
    "Feelin' U",
    'Chun-Li',
    'Bummerland',
    'Keep You Safe',
    'Alright (feat. Trippie Redd & Preme)',
    'Way Out (feat. Big Sean)',
    'THINK ABOUT ME',
    'Girls Have Fun (feat. G-Eazy & Rich The Kid)',
    'What You Know Bout Love',
    'for mah girl',
    'By Your Side (feat. Tom Grennan) - Oliver Heldens Remix',
    "'Till I Collapse",
    'Main Dhoondne Ko Zamaane Mein (From "Heartless")',
    'The Imitation Game',
    'Light of the Seven',
    'Astronaut In The Ocean',
    '24 (feat. Lil Baby)',
    'OUT WEST (feat. Young Thug)',
    'Lie',
    'Dirty Dancer',
    'Push & Pull',
    'She Gets the Flowers',
    'Never Be Lonely',
    'Through The Storm',
    'Sweater Weather',
    'See You Again (feat. Charlie Puth)',
    'Daddy Issues',
    'XO',
    'Chandelier',
    'I Want You To Know',
    'Tick Tock (feat. 24kGoldn)',
    "Life's A Mess (feat. Halsey)",
    'Legends',
    "Hollywood's Bleeding",
    'Change My Clothes',
    'Hurricane',
    'Donda Chant',
    'Jail',
    'Donda',
    'Close Your Eyes - Spotify Singles',
    'Stay A Little Longer',
    'older',
    'Jesus Lord pt 2',
    'Believe What I Say',
    'Reasons',
    'NIGHTRIDER',
    'TLC',
    'No Promises (feat. Demi Lovato)',
    'rockstar (feat. 21 Savage)',
    'Congratulations',
    'Better Now',
    'Only Wanna Be With You - Pokémon 25 Version',
    'Tattoo',
    'Bad Habits - Acoustic Version',
    'Addict Of Magic',
    'You should be sad',
    'Psycho (feat. Ty Dolla $ign)',
    'Not Afraid',
    'exile',
    "my ex's best friend (with blackbear)",
    'exile (feat. Bon Iver) - the long pond studio sessions',
    'Is It Just Me? (feat. Charlie Puth)',
    'Getaway Car',
    'Feel',
    'Dancing With Your Ghost',
    'Tightrope',
    'Liability',
    'willow',
    'Walked Through Hell',
    'could cry just thinkin about you - Full Version',
    'Toxic',
    'Insane',
    'Nit Nit',
    'Saint-Tropez',
    "Can't Be Touched (feat. Mr. Magic & Trouble)",
    'Superman',
    'RAP DEVIL',
    'Warm Up',
    'Numb / Encore',
    'Remember the Name (feat. Styles of Beyond)',
    'Remember The Name (feat. Eminem & 50 Cent)',
    'Space Bound',
    'We Own It (Fast & Furious)',
    'Purple Lamborghini (with Rick Ross)',
    'Broken',
    'Waiting',
    'Hurts Sometimes (with Jonathan Mendelsohn)',
    "Didn't I",
    'Youngblood',
    "don't say you love me",
    'Just For Me (with SZA) - Space Jam: A New Legacy',
    'Or Nah (feat. The Weeknd, Wiz Khalifa & DJ Mustard) - Remix',
    'Violent',
    "don't fall",
    'the way that you see me (feat. Ayleen Valentine)',
    'say goodbye',
    "Can't Trust A Soul",
    'Me and You',
    'Waka Waka (This Time for Africa) [The Official 2010 FIFA World Cup (TM) Song] (feat. Freshlyground)',
    'Girls Want Girls (with Lil Baby)',
    'Apricots',
    'the long way home (feat. Sara Kays & Sarcastic Sounds)',
    'Thot Shit',
    'Old Friends',
    'What If I Told You That I Love You',
    'Hide and Seek',
    'Rockstar',
    '10,000 Hours (with Justin Bieber)',
    "I Don't Care (with Justin Bieber)",
    'Lose You To Love Me',
    'Here With Me',
    'The Middle',
    'Girls Like You',
    'Unbelievable',
    'Easier',
    'Blank Space',
    'Post Malone (feat. RANI)',
    'Million Ways',
    "Fallin' All In You",
    'Lie To Me (feat. Julia Michaels)',
    "fuck, i'm lonely (with Anne-Marie)",
    'Jocelyn Flores',
    'XO Tour Llif3',
    '4 Da Gang (with Roddy Ricch)',
    'Walk Down',
    "They Ain't You",
    'No I in Team',
    'Tip Toe (feat. A Boogie Wit da Hoodie)',
    'Tyler Herro',
    'Iris',
    'Ugly',
    'Try',
    'Apologize',
    "She Doesn't Mind",
    'Got 2 Luv U (feat. Alexis Jordan)',
    'White Flag',
    'Underwater',
    'Everytime',
    'Because of You',
    'Relax, Take It Easy',
    'All Good Things (Come To An End) - Spanish Version',
    'Bleeding Love - Radio Edit',
    'Umbrella - Radio Edit',
    'Say It Right',
    'Torn',
    'POPSTAR (feat. Drake)',
    'GREECE (feat. Drake)',
    'LET IT GO (feat. Justin Bieber & 21 Savage)',
    'Lightskin Lil Wayne',
    'Life Is Good (feat. Drake)',
    'Whats Poppin (feat. DaBaby, Tory Lanez & Lil Wayne) [Remix] - Bonus Track',
    'Roses - Imanbek Remix [Latino Gang]',
    'I Won',
    'His & Hers (feat. Don Toliver, Lil Uzi Vert & Gunna)',
    'Move Ya Hips (feat. Nicki Minaj & MadeinTYO)',
    'Thrusting (feat. Swae Lee & Future)',
    'Lemonade - Remix',
    'Goddamn (feat. A Boogie wit da Hoodie)',
    'Moana',
    'Turks (with Gunna & ft. Travis Scott)',
    'All the Smoke (feat. Gunna & Wiz Khalifa)',
    'Baby (Lil Baby feat. DaBaby)',
    'Plain Jane REMIX (feat. Nicki Minaj)',
    'Tommy Lee (feat. SAINt JHN & Post Malone) - Remix',
    'No Brainer (feat. Justin Bieber, Chance the Rapper & Quavo)',
    'Ric Flair Drip (& Metro Boomin)',
    'Racks 2 Skinny',
    'Still Wiz',
    'High Right Now (feat. Wiz Khalifa) - Remix',
    'I DID IT (feat. Post Malone, Megan Thee Stallion, Lil Baby & DaBaby)',
    'Jealous (feat. Chris Brown, Lil Wayne & Big Sean)',
    'Used To Be - Rasster Remix',
    'I WANNA SEE SOME ASS (feat. jetsonmade)',
    'Tryna F**k Me (feat. Post Malone)',
    'Way down We Go',
    'Sorry',
    'Chanel Bag',
    'Lowkey',
    'Runnin (with A$AP Rocky, A$AP Ferg & Nicki Minaj)',
    'Go Crazy',
    'Going Bad (feat. Drake)',
    'Down Below',
    'Roses Remix (feat. Future)',
    'Dil Haare',
    'Jiyein Kyun',
    'Roadtrip',
    'Agar Tum Saath Ho (From "Tamasha")',
    'Jeena Jeena (From "Badlapur")',
    "Valentine's Mashup 2019",
    'Tere Sang Yaara',
    'Pehli Nazar Mein',
    'Pehli Dafa',
    'Paris (feat. GASHI)',
    'Kindness',
    'Touch It',
    'In My Bed',
    'Vibration',
]

export { songs, songsName }